version: '3.9'
services:
  yasgui:
    build:
      context: ./yasgui
      dockerfile: Dockerfile
    image: 'echoes/yasgui:4.2.8'
    container_name: yasgui
    environment:
      DEFAULT_SPARQL_ENDPOINT: '${DEFAULT_SPARQL_ENDPOINT}'
    ports:
      - '${EXPOSE_YASGUI_PORT}:80'