version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 99
  target-branch: develop
  ignore:
  - dependency-name: com.auth0:jwks-rsa
    versions:
    - 0.15.0
    - 0.17.0
  - dependency-name: org.glassfish.jersey.media:jersey-media-json-jackson
    versions:
    - 3.0.0
  - dependency-name: org.eclipse.jetty:jetty-servlet
    versions:
    - 11.0.0
    - 11.0.1
  - dependency-name: joda-time:joda-time
    versions:
    - 2.10.9
  - dependency-name: com.auth0:auth0
    versions:
    - 1.25.0
    - 1.26.0
    - 1.27.0
    - 1.28.0
  - dependency-name: org.glassfish.jersey.containers:jersey-container-jetty-http
    versions:
    - 3.0.0
  - dependency-name: org.eclipse.jetty:jetty-maven-plugin
    versions:
    - 11.0.0
    - 11.0.1
  - dependency-name: org.eclipse.jetty:jetty-nosql
    versions:
    - 11.0.0
    - 11.0.1
  - dependency-name: com.auth0:java-jwt
    versions:
    - 3.12.0
    - 3.12.1
    - 3.13.0
    - 3.14.0
  - dependency-name: org.glassfish.jersey.test-framework.providers:jersey-test-framework-provider-jdk-http
    versions:
    - 3.0.0
  - dependency-name: org.glassfish.jersey.inject:jersey-hk2
    versions:
    - 3.0.0
  - dependency-name: org.json:json
    versions:
    - "20201115"
  - dependency-name: org.glassfish.jersey.containers:jersey-container-servlet-core
    versions:
    - 3.0.0
  - dependency-name: com.fasterxml.jackson.core:jackson-core
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: com.fasterxml.jackson.core:jackson-annotations
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: org.eclipse.jetty:jetty-util
    versions:
    - 11.0.0
    - 11.0.1
  - dependency-name: net.sf.saxon:Saxon-HE
    versions:
    - "10.3"
  - dependency-name: org.apache.logging.log4j:log4j-iostreams
    versions:
    - 2.14.0
  - dependency-name: org.apache.logging.log4j:log4j-api
    versions:
    - 2.14.0
  - dependency-name: org.apache.logging.log4j:log4j-core
    versions:
    - 2.14.0
  - dependency-name: org.glassfish.jersey.core:jersey-common
    versions:
    - 3.0.0
  - dependency-name: org.glassfish.jersey.media:jersey-media-moxy
    versions:
    - 3.0.0
  - dependency-name: org.glassfish.jersey.core:jersey-server
    versions:
    - 3.0.0
  - dependency-name: org.glassfish.jersey:jersey-bom
    versions:
    - 3.0.0
  - dependency-name: io.reactivex.rxjava2:rxjava
    versions:
    - 2.2.20
  - dependency-name: com.squareup.moshi:moshi-adapters
    versions:
    - 1.11.0
  - dependency-name: com.squareup.moshi:moshi
    versions:
    - 1.11.0
  - dependency-name: org.mongodb:bson
    versions:
    - 3.12.7
  - dependency-name: org.mongodb:mongo-java-driver
    versions:
    - 3.12.7
  - dependency-name: org.apache.commons:commons-lang3
    versions:
    - "3.11"
