language: java
services: mongodb

sudo: false

jdk:
  - oraclejdk8

before_install:
  - git submodule update --init --recursive

script: mvn clean install cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - pir@csuc.cat
    on_success: always # default: change
    on_failure: always # default: always
